allowBuilds:
  esbuild: true
  protobufjs: true
minimumReleaseAge: 4320

blockExoticSubdeps: true

trustPolicy: "no-downgrade"

strictDepBuilds: true

ignoreScripts: true

trustPolicyExclude:
  - undici-types